const STORAGE_KEY='worklist.tasks.v1';
const HEADERS=['Task','Status','Priority','Project','Due Date','Completed Date','Waiting On','Notes'];
const ACTIVE=['Not Started','In Progress','Waiting','Blocked'];
let tasks=loadTasks(), view='active';
const $=id=>document.getElementById(id);
const active=s=>ACTIVE.includes(s);
const rank=p=>({'P0 Urgent':0,'P1 High':1,'P2 Normal':2,'P3 Later':3}[p]??9);
const today=()=>{const d=new Date(),o=d.getTimezoneOffset();return new Date(d.getTime()-o*60000).toISOString().slice(0,10)};
const esc=s=>String(s??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]||m));
const uid=()=>globalThis.crypto?.randomUUID?.()||('t_'+Date.now()+'_'+Math.random().toString(36).slice(2));
function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),1900)}
function loadTasks(){try{const v=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(tasks))}
function normalize(x={}){return{id:x.id||uid(),task:String(x.task||'').trim(),status:String(x.status||'Not Started'),priority:String(x.priority||'P2 Normal'),project:String(x.project||'').trim(),due:String(x.due||''),completed:String(x.completed||''),waiting:String(x.waiting||'').trim(),notes:String(x.notes||'').trim()}}
function stats(){$('sActive').textContent=tasks.filter(t=>active(t.status)).length;$('activeCount').textContent=$('sActive').textContent;$('sToday').textContent=tasks.filter(t=>active(t.status)&&t.due===today()).length;$('sWaiting').textContent=tasks.filter(t=>['Waiting','Blocked'].includes(t.status)).length;$('sDone').textContent=tasks.filter(t=>t.status==='Completed').length}
function rows(){const q=$('search').value.toLowerCase(),p=$('project').value,pr=$('priority').value;return tasks.filter(t=>{if(view==='active'&&!active(t.status))return false;if(view==='today'&&!(active(t.status)&&(t.due===today()||t.priority==='P0 Urgent')))return false;if(view==='waiting'&&!['Waiting','Blocked'].includes(t.status))return false;if(view==='completed'&&t.status!=='Completed')return false;if(p&&t.project!==p)return false;if(pr&&t.priority!==pr)return false;if(q&&!`${t.task} ${t.project} ${t.notes} ${t.waiting}`.toLowerCase().includes(q))return false;return true}).sort((a,b)=>rank(a.priority)-rank(b.priority)||(a.due||'9999').localeCompare(b.due||'9999'))}
function render(){stats();const ps=[...new Set(tasks.map(t=>t.project).filter(Boolean))].sort(),cur=$('project').value;$('project').innerHTML='<option value="">All projects</option>'+ps.map(x=>`<option>${esc(x)}</option>`).join('');$('project').value=cur;const r=rows();$('list').innerHTML=r.map(t=>`<article class="card"><div><div class="task-title">${esc(t.task)}</div><div class="meta"><span class="pill">${esc(t.priority)}</span><span>${esc(t.status)}</span>${t.project?`<span>• ${esc(t.project)}</span>`:''}${t.due?`<span>• Due ${esc(t.due)}</span>`:''}${t.completed?`<span>• Completed ${esc(t.completed)}</span>`:''}${t.waiting?`<span>• Waiting on ${esc(t.waiting)}</span>`:''}</div>${t.notes?`<div class="notes">${esc(t.notes)}</div>`:''}</div><div class="actions">${t.status!=='Completed'?`<button data-done="${t.id}">Done</button>`:''}<button data-edit="${t.id}">Edit</button></div></article>`).join('');$('empty').classList.toggle('hidden',r.length>0);document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>complete(b.dataset.done));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit))}
function complete(id){const t=tasks.find(x=>x.id===id);if(!t)return;t.status='Completed';t.completed=t.completed||today();save();render();toast('Task completed')}
function openEdit(id=null){const t=id===null?{}:tasks.find(x=>x.id===id)||{};$('row').value=id||'';$('dialogTitle').textContent=id===null?'Add task':'Edit task';$('task').value=t.task||'';$('status').value=t.status||'Not Started';$('prio').value=t.priority||'P2 Normal';$('proj').value=t.project||'';$('due').value=t.due||'';$('waiting').value=t.waiting||'';$('notes').value=t.notes||'';$('dialog').showModal()}
function addTask(payload){const n=normalize(payload);if(!n.task)throw new Error('Task is required.');const dup=tasks.find(t=>active(t.status)&&t.task.toLowerCase()===n.task.toLowerCase());if(dup)throw new Error('A matching active task already exists.');tasks.push(n);save();return n}
function updateTask(id,payload){const i=tasks.findIndex(x=>x.id===id);if(i<0)throw new Error('Task not found.');const previous=tasks[i],next=normalize({...previous,...payload,id});if(next.status==='Completed'&&!next.completed)next.completed=today();if(next.status!=='Completed'&&payload.status)next.completed='';tasks[i]=next;save()}
function parseNotes(text=''){const lines=String(text).split(/\n+/).map(s=>s.trim()).filter(Boolean).filter(s=>!/^https?:\/\//i.test(s));const action=/\b(create|make|build|send|follow up|meet|ask|confirm|determine|investigate|review|get|define|prepare|outline|bring|schedule|start|work on|understand|check|figure out|create ticket|finalize|draft|test|validate|coordinate)\b/i;const context=[],out=[];for(const line of lines){if(line.length>300){context.push(line);continue}let task='';if(action.test(line))task=line.replace(/^[-*•\d.)\s]+/,'').trim();else if(/[?]$/.test(line))task='Determine '+line.replace(/[?]+$/,'').trim();if(task){task=task.charAt(0).toUpperCase()+task.slice(1);if(!/[.!?]$/.test(task))task+='.';out.push({task,notes:line})}else context.push(line)}const unique=[...new Map(out.map(x=>[x.task.toLowerCase(),x])).values()];if(context.length&&unique.length===1)unique[0].notes=[unique[0].notes,...context].join(' | ');return unique}
function csvEscape(v=''){v=String(v??'');return /[",\n\r]/.test(v)?'"'+v.replace(/"/g,'""')+'"':v}
function toCSV(){return [HEADERS.join(','),...tasks.map(t=>[t.task,t.status,t.priority,t.project,t.due,t.completed,t.waiting,t.notes].map(csvEscape).join(','))].join('\n')+'\n'}
function parseCSV(s){const rows=[];let row=[],cell='',q=false;for(let i=0;i<s.length;i++){const c=s[i];if(q){if(c==='"'&&s[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(c!=='\r')cell+=c}}if(cell.length||row.length){row.push(cell);rows.push(row)}return rows}
function fromCSV(text){const rows=parseCSV(text).filter(r=>r.some(x=>String(x).trim()!==''));if(!rows.length)return[];const h=rows.shift().map(x=>x.trim()),ix=n=>h.indexOf(n);if(ix('Task')<0)throw new Error('CSV must include a Task column.');return rows.map(r=>normalize({task:r[ix('Task')]||'',status:r[ix('Status')]||'Not Started',priority:r[ix('Priority')]||'P2 Normal',project:r[ix('Project')]||'',due:r[ix('Due Date')]||'',completed:r[ix('Completed Date')]||'',waiting:r[ix('Waiting On')]||'',notes:r[ix('Notes')]||''})).filter(t=>t.task)}
$('addBtn').onclick=()=>openEdit();$('close').onclick=$('cancel').onclick=()=>$('dialog').close();
$('form').onsubmit=e=>{e.preventDefault();const id=$('row').value,payload={task:$('task').value,status:$('status').value,priority:$('prio').value,project:$('proj').value,due:$('due').value,waiting:$('waiting').value,notes:$('notes').value};try{if(!id)addTask(payload);else updateTask(id,payload);$('dialog').close();render();toast(!id?'Task added':'Task updated')}catch(err){toast(err.message)}};
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');view=b.dataset.view;const map={active:['Active Tasks','Everything that still needs action.'],today:['Today','Urgent and due-today work.'],waiting:['Waiting / Blocked','Dependencies that need attention.'],completed:['Completed','Your searchable accomplishment history.'],all:['All Tasks','Every task in the ledger.']};$('title').textContent=map[view][0];$('subtitle').textContent=map[view][1];render()});
['search','project','priority'].forEach(id=>$(id).addEventListener('input',render));
$('extractBtn').onclick=()=>{const text=$('noteInput').value.trim();if(!text)return;const p=parseNotes(text),box=$('proposals');box.classList.remove('hidden');if(!p.length){box.innerHTML='<p>No clear actions found.</p>';return}box.innerHTML='<strong>Proposed actions</strong>'+p.map((x,i)=>`<label class="proposal"><input type="checkbox" checked data-i="${i}"><span>${esc(x.task)}<small>${esc(x.notes)}</small></span></label>`).join('')+'<div class="row"><button id="saveProposals" class="primary">Add selected</button></div>';box.dataset.items=JSON.stringify(p);$('saveProposals').onclick=()=>{const items=JSON.parse(box.dataset.items);let added=0;for(const c of box.querySelectorAll('input[type=checkbox]:checked')){try{addTask({task:items[+c.dataset.i].task,status:'Not Started',priority:'P2 Normal',notes:items[+c.dataset.i].notes});added++}catch{}}toast(`${added} task${added===1?'':'s'} added`);box.classList.add('hidden');$('noteInput').value='';render()}};
$('clearBtn').onclick=()=>{$('noteInput').value='';$('proposals').classList.add('hidden')};
$('exportBtn').onclick=()=>{const blob=new Blob([toCSV()],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='GPT To Do Database.csv';document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url);toast('CSV exported')};
$('importBtn').onclick=()=>$('importFile').click();
$('importFile').onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{const incoming=fromCSV(await file.text());if(!confirm(`Replace this browser's current ${tasks.length} tasks with ${incoming.length} imported tasks?`))return;tasks=incoming;save();render();toast('CSV imported')}catch(err){toast(err.message)}finally{e.target.value=''}};
render();
